---
- hosts: all
  gather_facts: false
  # connection: local
  become: true

  tasks:
  - name: run on master and worker
    script: "./update.sh"


  - name: run on master
    script: "./script2.sh"
    register: result
    delegate_to: master

  # - name: test
  #   command: "apt install wget -y"
  #   register: result

  - name: print output
    debug:
      var: result
  
