---
- hosts: k8s_node
  gather_facts: false
  # connection: local
  become: true

  tasks:
  - name: eks script
    script: "./update.sh"
    #register: result

  - name: eks script2
    script: "./script2.sh"
    register: result

  # - name: test
  #   command: "apt install wget -y"
  #   register: result

  - name: print output
    debug:
      var: result
  
