---
- hosts: k8s_node
  gather_facts: false
  # connection: local
  become: true

  tasks:
  - name: Apt update
    script: "./update.sh"
    register: result

  - name: print output
    debug:
      var: result
  
